### ISSUE TITLE
Nested RSCs

### ISSUE THREAD

**Issue by mhuretski** [jherr/better-rscs#1]
https://codesandbox.io/p/sandbox/jovial-tesla-1ppiwj?file=%2Fapp%2Fpage.js

**Comment by jherr** [comment]
True. What's happening there is that NextJS is resolving all the server components and their async work first. And that result is going off to the client, and then the client is simply showing and hiding the pre-rendered server component. It's not going back to the server to get a new server component if any properties on that server component had changed.

On the plus side it hasn't fully promoted the server component to a client component, it doesn't re-render it. Which is cool.

**Comment by mhuretski** [comment]
I didn't promise server component will change on client props change, I just wanted to highlight it's possible to nest them and in some scenarios it's very useful.

**Comment by jherr** [comment]
I see. I don't disagree that nested RSCs that fetch their data is very cool. Though it can potentially lead to an anti-pattern if a lot of nested components fetch data. There is also another anti-pattern to avoid where data is prop-drilled from the top as the way NextJS persists the DOM between the server and the client includes copies of the data at each level of the drilling, which can lead to large pages _in memory_. Yes, gzip helps with that issues, but multiple megabytes of JSON still takes up a lot of time to parse and space to store.
